import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { AlertTriangle, Gauge, Info, TrendingDown } from "lucide-react";
import { useBundle } from "@/hooks/useBundle";
import { useCopilot, useFmt } from "@/data/store";
import { t as copy } from "@/i18n";
import { Banner, Card, CardHeader, Chip, Grid, Meter, PageHeader, Segmented, Stat, Table } from "@/components/ui";
import { EvidenceBody, EvidenceButton } from "@/components/Evidence";
import { ForecastChart, MoneyBars, Panel, VIZ } from "@/components/charts";
import { HORIZONS, runForecast } from "@/engines/forecast";
import { fullDate } from "@/lib/format";
export default function Forecast() {
    const bundle = useBundle();
    const f = useFmt();
    const { lang } = useCopilot();
    const [horizon, setHorizon] = useState(30);
    if (!bundle)
        return null;
    const { ctx, forecast30, forecast90, monthEnd, shortage, shortageRisk, backtest } = bundle;
    const fc = horizon === 90 ? forecast90 : horizon === 30 ? forecast30 : runForecast(ctx, horizon);
    const risky = forecast30.lowBalanceWindows.length > 0;
    return (_jsxs("div", { children: [_jsx(PageHeader, { title: copy("forecast", lang), subtitle: f.loc === "bn"
                    ? "দুটি মডেল একসাথে চালানো হয় — আপনার সাম্প্রতিক গড়, আর মৌসুম-সচেতন মডেল — যাতে বাস্তবতার সঙ্গে তুলনা করা যায়।"
                    : "Two models run side by side: the recent-average a customer would eyeball, and a seasonality-aware model. The gap between them is the honest uncertainty.", actions: _jsx(Segmented, { value: String(horizon), onChange: (v) => setHorizon(Number(v)), options: HORIZONS.map((h) => ({ value: String(h), label: `${h} ${copy("days", lang)}` })) }) }), _jsxs(Grid, { cols: 4, className: "mb-5", children: [_jsx(Card, { children: _jsx(Stat, { label: f.loc === "bn" ? "আজকের তরল ব্যালেন্স" : "Liquid balance today", value: f.taka(ctx.liquidBalance), big: true, hint: f.fullDate(ctx.asOf) }) }), _jsx(Card, { children: _jsx(Stat, { label: `${horizon} ${copy("days", lang)} ${f.loc === "bn" ? "আয়" : "income"}`, value: f.taka(fc.expectedIncome), tone: "good", hint: f.loc === "bn" ? "নিয়মিত ও অনিয়মিত মিলিয়ে" : "scheduled + irregular" }) }), _jsx(Card, { children: _jsx(Stat, { label: `${horizon} ${copy("days", lang)} ${f.loc === "bn" ? "ব্যয়" : "spending"}`, value: f.taka(fc.expectedExpense), hint: `${f.loc === "bn" ? "দৈনিক গড়" : "daily rate"} ${f.taka(fc.expectedExpense / Math.max(1, horizon))} · ${f.loc === "bn" ? "বাধ্যতামূলক" : "obligations"} ${f.taka(fc.points.reduce((a, p) => a + p.recurringDue, 0))}` }) }), _jsx(Card, { children: _jsx(Stat, { label: f.loc === "bn" ? "শেষ ব্যালেন্স (প্রকৃতিপত)" : "Projected closing", value: f.taka(fc.expectedEndingBalance), tone: fc.expectedEndingBalance < fc.buffer ? "bad" : "good", big: true, hint: `${f.loc === "bn" ? "সর্বনিম্ন" : "trough"} ${f.taka(fc.minBalance)} ${fc.minBalanceDate ? `· ${fullDate(fc.minBalanceDate, f.tlang)}` : ""}` }) })] }), risky ? (_jsx("div", { className: "mb-5", children: _jsx(Banner, { tone: "warn", title: `${copy("forecast_shortage", lang)} · ${shortageRisk}`, icon: _jsx(AlertTriangle, { className: "h-4 w-4" }), children: _jsx("p", { children: f.loc === "bn"
                            ? `${f.fullDate(fc.lowBalanceWindows[0].from)} থেকে ${f.fullDate(fc.lowBalanceWindows[0].to)} পর্যন্ত ব্যালেন্স ${f.taka(fc.buffer)} রিজার্ভের নিচে নামার সম্ভাবনা আছে।`
                            : `The model puts the balance under the ${f.taka(fc.buffer)} buffer between ${f.fullDate(fc.lowBalanceWindows[0].from)} and ${f.fullDate(fc.lowBalanceWindows[0].to)}. Late-month spending is ${f.percent(shortage.lateShare, 0)} of the month.` }) }) })) : null, _jsx("div", { className: "mb-5", children: _jsx(Panel, { title: f.loc === "bn" ? `${horizon} দিনের পূর্বাভাস` : `${horizon}-day projection`, subtitle: f.loc === "bn"
                        ? "ছায়া অংশ = আস্থা ব্যাপ্তি; কমলা রেখা = নিরাপত্তা রিজার্ভ"
                        : "Shaded band is the uncertainty range; the dashed line is the safety buffer.", right: _jsxs("div", { className: "text-right", children: [_jsx("div", { className: "text-[11px] font-semibold text-ink-400 uppercase", children: copy("confidence", lang) }), _jsx("div", { className: "tabular text-[14px] font-bold text-ink-900", children: f.percent(fc.confidence, 0) })] }), height: 320, children: _jsx(ForecastChart, { points: fc.points, lang: f.tlang, buffer: fc.buffer, height: 320 }) }) }), _jsxs(Grid, { cols: 3, className: "mb-5", children: [_jsx(Panel, { title: f.loc === "bn" ? "দৈনিক বিভাজন" : "Day-by-day movement", subtitle: f.loc === "bn" ? "আয় বনাম ব্যয়" : "income vs spending", height: 230, children: _jsx(MoneyBars, { lang: f.tlang, height: 230, data: fc.points.map((p) => ({ date: p.date, income: p.income, expense: p.expense })), keys: [
                                { key: "income", label: f.loc === "bn" ? "আয়" : "income", color: VIZ[1] },
                                { key: "expense", label: f.loc === "bn" ? "ব্যয়" : "spend", color: VIZ[0] },
                            ] }) }), _jsx(Panel, { title: f.loc === "bn" ? "মডেল বনাম বেসলাইন" : "Model vs the eyeball baseline", subtitle: f.loc === "bn" ? "ব্যাকটেস্টিং-এ পরিমাপ করা" : "measured by backtesting, not asserted", height: 230, children: _jsxs("div", { className: "space-y-3", children: [_jsx(Stat, { label: f.loc === "bn" ? "মডেলের গড় নির্ভুলতা (MAE)" : "Model mean absolute error", value: f.taka(backtest.maeModel), tone: "good", hint: `${f.num(backtest.windows)} ${f.loc === "bn" ? "টি উইন্ডোতে" : "windows"} · ${f.pct(backtest.improvementPct, 0)} ${f.loc === "bn" ? "ভালো" : "better than baseline"}` }), _jsx(Stat, { label: f.loc === "bn" ? "বেসলাইন MAE" : "Baseline mean absolute error", value: f.taka(backtest.maeBaseline), tone: "warn" }), _jsx("div", { children: _jsx(Meter, { value: backtest.maeModel, max: Math.max(backtest.maeBaseline, backtest.maeModel, 1), tone: backtest.maeModel <= backtest.maeBaseline ? "good" : "warn", label: f.loc === "bn" ? "তুলনামূলক নির্ভুলতা" : "relative accuracy" }) }), _jsx("p", { className: "text-[11.5px] leading-relaxed text-ink-500", children: f.loc === "bn"
                                        ? `প্রতিটি উইন্ডোর পরে ভবিষ্যৎকে আড়াল করে মডেল চালিয়ে প্রকৃত ব্যালেন্সের সাথে মিলিয়ে দেখা হয়। MAPE: মডেল ${f.percent(backtest.mapeModel / 100, 1)} বনাম বেসলাইন ${f.percent(backtest.mapeBaseline / 100, 1)}।`
                                        : `Each window hides the future, runs the model, and compares against what actually happened. MAPE: model ${f.percent(backtest.mapeModel / 100, 1)} vs baseline ${f.percent(backtest.mapeBaseline / 100, 1)}.` })] }) }), _jsx(Panel, { title: f.loc === "bn" ? "মাস শেষের দৃশ্য" : "Month-end view", subtitle: `${monthEnd.daysRemaining} ${copy("days", lang)} ${f.loc === "bn" ? "বাকি" : "remaining"}`, height: 230, children: _jsxs("div", { className: "space-y-3", children: [_jsx(Stat, { label: f.loc === "bn" ? "এই মাসে এখন পর্যন্ত" : "So far this month", value: f.taka(monthEnd.monthSoFar.spend), hint: `${f.loc === "bn" ? "আয়" : "income"} ${f.taka(monthEnd.monthSoFar.income)}` }), _jsx(Stat, { label: f.loc === "bn" ? "মাস শেষে প্রকৃতিপত" : "Projected at month end", value: f.taka(monthEnd.forecast.expectedEndingBalance), tone: monthEnd.forecast.expectedEndingBalance < monthEnd.forecast.buffer ? "bad" : "good", big: true }), _jsxs("div", { className: "rounded-xl border border-ink-200 bg-ink-50 p-3", children: [_jsx("div", { className: "mb-1 text-[11px] font-bold tracking-wide text-ink-400 uppercase", children: f.loc === "bn" ? "ঝুঁকির মাত্রা" : "Shortage risk" }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Gauge, { className: "h-4 w-4 text-ink-500" }), _jsx("span", { className: "text-[13px] font-bold text-ink-900 capitalize", children: shortageRisk })] }), _jsx("p", { className: "mt-1 text-[11.5px] leading-relaxed text-ink-600", children: f.loc === "bn"
                                                ? `ঘাটতির সম্ভাবনা ${f.percent(shortage.lowBalanceProbability, 0)}, প্রস্তাবিত সর্বনিম্ন ব্যালেন্স ${f.taka(shortage.projectedMinBalance)}।`
                                                : `${f.percent(shortage.lowBalanceProbability, 0)} probability of dipping below the buffer, with a projected low of ${f.taka(shortage.projectedMinBalance)}.` }), shortage.suggestedReduction > 0 ? (_jsx("p", { className: "mt-1 text-[11.5px] font-semibold text-brand-700", children: f.loc === "bn"
                                                ? `প্রায় ${f.taka(shortage.suggestedReduction)} কমালে ঘাটতি পূরণ হবে।`
                                                : `Trimming about ${f.taka(shortage.suggestedReduction)} of late-month discretionary spend closes the gap.` })) : null] })] }) })] }), _jsxs(Card, { className: "mb-5", children: [_jsx(CardHeader, { kicker: f.loc === "bn" ? "মাসের শেষ ভাগ কেন সমস্যা" : "Why the last third of the month hurts", title: f.loc === "bn" ? "ব্যয়ের কারণ ভাঙাভাঙি" : "Decomposition of the late-month spend", right: _jsx(EvidenceButton, { evidence: shortage.evidence }) }), _jsxs(Grid, { cols: 3, children: [_jsx(Stat, { label: f.loc === "bn" ? "১–১০ তারিখ" : "Days 1–10", value: f.taka(shortage.earlySpend) }), _jsx(Stat, { label: f.loc === "bn" ? "১১–২০ তারিখ" : "Days 11–20", value: f.taka(shortage.midSpend) }), _jsx(Stat, { label: f.loc === "bn" ? "২১ তারিখের পর" : "After day 20", value: f.taka(shortage.lateSpend), tone: "bad", hint: `${f.percent(shortage.lateShare, 0)} ${copy("total", lang).toLowerCase()}` })] }), _jsx("div", { className: "mt-4", children: _jsx(Table, { align: "right", head: [
                                f.loc === "bn" ? "খাত" : "Category",
                                f.loc === "bn" ? "পরিমাণ" : "Amount",
                                f.loc === "bn" ? "অংশ" : "Share",
                                f.loc === "bn" ? "সংখ্যা" : "Transactions",
                            ], rows: shortage.contributors.slice(0, 8).map((c) => [
                                _jsx("span", { className: "font-semibold text-ink-800 capitalize", children: c.category }),
                                f.taka(c.amount),
                                f.percent(c.share, 0),
                                f.num(c.count),
                            ]) }) })] }), _jsxs(Card, { children: [_jsx(CardHeader, { kicker: copy("evidence", lang), title: fc.evidence.headline, right: _jsxs(Chip, { tone: "neutral", children: [Math.round(fc.evidence.confidence * 100), "% ", copy("confidence", lang)] }) }), _jsx(EvidenceBody, { evidence: fc.evidence }), _jsxs("div", { className: "mt-4 flex items-start gap-2 text-[11.5px] leading-relaxed text-ink-500", children: [_jsx(Info, { className: "mt-0.5 h-3.5 w-3.5 shrink-0" }), _jsx("p", { children: f.loc === "bn"
                                    ? `ধরণাবিধান: ${fc.evidence.assumptions.join(" ")}`
                                    : `Assumptions in force: ${fc.evidence.assumptions.join(" ")}` })] })] }), _jsxs("div", { className: "mt-5 grid gap-3 sm:grid-cols-2", children: [_jsxs(Card, { children: [_jsx(CardHeader, { title: f.loc === "bn" ? "আয় আসার প্যাটার্ন" : "When income arrives" }), _jsx(Table, { align: "right", head: [f.loc === "bn" ? "উৎস" : "Source", f.loc === "bn" ? "গড়" : "Average", f.loc === "bn" ? "সাধারণ দিন" : "Typical day", f.loc === "bn" ? "স্থিতিশীলতা" : "Stability"], rows: bundle.sources.incomeSources.slice(0, 6).map((s) => [
                                    s.label,
                                    f.taka(s.amount / Math.max(1, s.occurrences)),
                                    s.typicalDay ? f.num(s.typicalDay) : "—",
                                    _jsx(Chip, { tone: s.stability >= 0.8 ? "good" : s.stability >= 0.5 ? "warn" : "bad", children: f.percent(s.stability, 0) }),
                                ]) })] }), _jsxs(Card, { children: [_jsx(CardHeader, { title: f.loc === "bn" ? "আসন্ন দায়বদ্ধতা" : "Obligations inside the horizon" }), _jsx(Table, { align: "right", head: [f.loc === "bn" ? "খাত" : "Item", f.loc === "bn" ? "পরিমাণ" : "Amount", f.loc === "bn" ? "দিন" : "Day", f.loc === "bn" ? "ধরন" : "Type"], rows: ctx.recurring.slice(0, 7).map((r) => [
                                    _jsx("span", { className: "font-semibold text-ink-800", children: r.expense_name }),
                                    f.taka(r.amount),
                                    f.num(r.due_day),
                                    r.mandatory ? (_jsx(Chip, { tone: "warn", children: f.loc === "bn" ? "বাধ্যতামূলক" : "mandatory" })) : (_jsx(Chip, { tone: "neutral", children: f.loc === "bn" ? "ঐচ্ছিক" : "optional" })),
                                ]) }), _jsx("p", { className: "mt-3 text-[11.5px] leading-relaxed text-ink-500", children: f.loc === "bn"
                                    ? "এই তালিকা ledger-এর সঙ্গে তুলনা করে স্বয়ংক্রিয়ভাবে শনাক্ত করা হয়েছে — অনুমান করা নয়।"
                                    : "This list was matched against the ledger rather than typed by hand, so the obligations priced into the forecast are the ones you actually paid." })] })] }), _jsx("div", { className: "mt-5", children: _jsxs(Banner, { tone: "info", icon: _jsx(TrendingDown, { className: "h-4 w-4" }), children: [_jsx("p", { className: "mb-1 font-semibold text-ink-800", children: f.loc === "bn" ? "পূর্বাভাস কী, কী নয়" : "What a forecast is — and is not" }), _jsx("p", { children: f.loc === "bn"
                                ? "এটি একটি সম্ভাবনার মডেল, ভবিষ্যদ্বাণ নয়। আয় সময়মতো না এলে, বা একটি বড় চাহিদা হঠাৎ এলে, প্রকৃত ফলাফল পার্থক্য হবে। তাই আমরা ব্যাপ্তি দেখাই এবং নিজে যাচাই করার সুযোগ দিই।"
                                : "This is a probability model, not a promise. If income arrives late, or an expense lands early, the outcome will differ — which is why the band is shown and the assumptions are listed rather than hidden." })] }) })] }));
}
